/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaciesEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kamini Prakash
 */
public class RequestPharmacistForMedicine extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    WorkRequest patientrequest;
    String medlist="";
   

    /**
     * Creates new form RequestPharmacistForMedicine
     */
    public RequestPharmacistForMedicine(JPanel userProcessContainer, WorkRequest request,
           Network network, UserAccount account, Enterprise enterprise )
           
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.patientrequest = request;
        txtPatientName.setText(patientrequest.getSender().getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkAca = new javax.swing.JCheckBox();
        chkDis = new javax.swing.JCheckBox();
        chkCam = new javax.swing.JCheckBox();
        chkAnt = new javax.swing.JCheckBox();
        chkViv = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(188, 194, 223));

        chkAca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkAca.setText("Acamprosate");
        chkAca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAcaActionPerformed(evt);
            }
        });

        chkDis.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkDis.setText("Disulfiram");
        chkDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDisActionPerformed(evt);
            }
        });

        chkCam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkCam.setText("Campral");

        chkAnt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkAnt.setText("Antabuse");
        chkAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAntActionPerformed(evt);
            }
        });

        chkViv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkViv.setText(" Vivitrol");
        chkViv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkVivActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Request Pharmacist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("For Patient");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPatientName.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText(" Prescription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAnt)
                            .addComponent(chkCam)
                            .addComponent(chkDis)
                            .addComponent(chkAca)
                            .addComponent(chkViv)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(45, 45, 45)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkAca)
                .addGap(30, 30, 30)
                .addComponent(chkDis)
                .addGap(32, 32, 32)
                .addComponent(chkCam)
                .addGap(27, 27, 27)
                .addComponent(chkAnt)
                .addGap(29, 29, 29)
                .addComponent(chkViv)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkAcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAcaActionPerformed

    private void chkDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDisActionPerformed

    private void chkAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAntActionPerformed

    private void chkVivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkVivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkVivActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        patientrequest.setSender(userAccount);
       // patientrequest.setReceiver();
        if (chkAca.isSelected())
        {
            medlist = medlist + " Acamprosate ,";
        
        }
        if (chkDis.isSelected())
        {
            medlist = medlist + "Disulfiram ,";
        
        }
       
        if(chkCam.isSelected())
        {
            medlist = medlist + "Campral ,";
        }
        if(chkAnt.isSelected())
        {
            medlist = medlist + "Antabuse ,";
        }
        if(chkViv.isSelected())
        {
            medlist = medlist + "Vivitrol ,";
        }
      
        System.out.println(medlist);
        patientrequest.setMedlist(medlist);
        patientrequest.setStatus("Prescription Given");
        patientrequest.setDiagnose("Following medicines have been prescribed : \n " + medlist );
        
      Organization org = null;
     for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
          if (enterprise instanceof PharmaciesEnterprise){     
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PharmacistOrganization){
                org = organization;                
                break;
            }
        }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(patientrequest);
            patientrequest.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(patientrequest);
        }
     }
        JOptionPane.showMessageDialog(null, "Medical prescription sent to pharmacist successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAca;
    private javax.swing.JCheckBox chkAnt;
    private javax.swing.JCheckBox chkCam;
    private javax.swing.JCheckBox chkDis;
    private javax.swing.JCheckBox chkViv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
