/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author sojit
 */
public class StatisticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticsJPanel
     */
   JPanel userProcessContainer;
   WorkRequest patientrequest;
   Network network;
   Enterprise enterprise;
   UserAccount userAccount;
   DoctorOrganization organization;

    public StatisticsJPanel(JPanel userProcessContainer, UserAccount userAccount, DoctorOrganization organization, Enterprise enterprise, Network network) {
         initComponents();         
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.organization = organization;
        Loadbarchart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        barchartRequeststatistics = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(188, 194, 223));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Request Statistics");

        barchartRequeststatistics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barchartRequeststatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(59, 59, 59)
                .addComponent(barchartRequeststatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barchartRequeststatistics;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void Loadbarchart() {
//        if (!(enterprise instanceof Enterprise)) {
//            JOptionPane.showMessageDialog(null, "Please add Enterprises.");
//            return;
//        };
           int count =0;
       
        int medhistcollected_count = 0;
        int resultfound_count = 0;
        int assigntodoc_count = 0;
        int sent_count = 0;
         int assigntophysio_count = 0;
           int assigntopsy_count = 0;
         //Assigned to psychiatrist
         for(WorkRequest workreq :organization.getWorkQueue().getWorkRequestList())
        {
            if(workreq.getStatus().equalsIgnoreCase("sent"))
            {
                sent_count++;
            }
            else if(workreq.getStatus().equalsIgnoreCase("result found"))
            {
                resultfound_count++;
            }
             else if(workreq.getStatus().equalsIgnoreCase("assigned to doc"))
            {
                assigntodoc_count++;
            }
             else if(workreq.getStatus().equalsIgnoreCase("Med Hist Collected For Lab"))
            {
                medhistcollected_count++;
            }
             else if(workreq.getStatus().equalsIgnoreCase("Assigned to pharmacotherapist"))
            {
                assigntophysio_count++;
            }
             else if(workreq.getStatus().equalsIgnoreCase("Assigned to psychiatrist"))
            {
                assigntopsy_count++;
            }
            
           // workreq
        }
        DefaultCategoryDataset DCategorydata = new DefaultCategoryDataset();

        DCategorydata.setValue(sent_count, "sent", "sent");        
        DCategorydata.setValue(assigntodoc_count, "assignedto doc", "assignedto doc");
        DCategorydata.setValue(resultfound_count, "Result Found", "Result Found");
        DCategorydata.setValue(medhistcollected_count, "Med hist collected lab", "Med hist collected lab");
        DCategorydata.setValue(assigntophysio_count, "Assigned to pharmacotherapist", "Assigned to pharmacotherapist");
        DCategorydata.setValue(assigntophysio_count, "Assigned to psychiatrist", "Assigned to psychiatrist");


        JFreeChart jfreechart = ChartFactory.createBarChart3D("PATIENT REQUEST STATISTICS", "ENTITIES", "COUNT", DCategorydata, PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot plot = jfreechart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);

        ChartPanel chartp = new ChartPanel(jfreechart, true);

        chartp.setVisible(true);
        barchartRequeststatistics.removeAll();
        barchartRequeststatistics.setLayout(new java.awt.BorderLayout());
        barchartRequeststatistics.add(chartp, BorderLayout.CENTER);
        barchartRequeststatistics.validate();
    }
}
