
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.RehabCentersEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PhysiotherapistOrganization;
import Business.Organization.PsychiatristOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

/**
 *
 * @author Kamini Prakash
 */
public class ViewLabResultcases extends javax.swing.JPanel {

    JPanel userProcessContainer;
    WorkRequest patientrequest;
    Network network;
    Enterprise enterprise;
    UserAccount userAccount;

      String emailId=null;

    /**
     * Creates new form ViewLabResultOverdoseCases
     */
    public ViewLabResultcases(JPanel userProcessContainer, WorkRequest request, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.patientrequest = request;
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        popupResult();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txt = new javax.swing.JTextField();
        txtResultType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResultbyLab = new javax.swing.JTextField();
        btnPsyc = new javax.swing.JButton();
        btnphrmaco = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnPrescription = new javax.swing.JButton();

        jLabel3.setText("Result");

        jLabel4.setText("Result Type");

        jLabel5.setText("Name");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtResultType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Solution By Lab");

        btnPsyc.setText("Send To Psychiatrist");
        btnPsyc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsycActionPerformed(evt);
            }
        });

        btnphrmaco.setText("Send To Pharmacotherapist");
        btnphrmaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphrmacoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Lab Process Result");

        jButton3.setText("< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnPrescription.setText("Write Prescription");
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnPsyc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addComponent(txt, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addComponent(txtResultType)
                                .addComponent(txtResultbyLab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnphrmaco)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrescription)
                                .addGap(83, 83, 83)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultType, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtResultbyLab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPsyc)
                    .addComponent(btnphrmaco)
                    .addComponent(jButton3)
                    .addComponent(btnPrescription))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>                        

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtResultTypeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void btnphrmacoActionPerformed(java.awt.event.ActionEvent evt) {                                           

           //Email Sending Part
        emailId = "sojitradharti15@gmail.com";
        
        String emailRegex = "^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$";
        
        Pattern pat = Pattern.compile(emailRegex); 
		if (emailId == null) 
                {
                    JOptionPane.showMessageDialog(null, "Please enter a valid email id. It should not start with _ and must contain an email Id with _, . and @ only!!");
                    return;
                }
			
                else
                {
                    if(!(pat.matcher(emailId).matches()) )
                    {
                        JOptionPane.showMessageDialog(null, "Please enter a valid email id. It should not start with _ and must contain an email Id with _, . and @ !!");
                        return;
                    }   
                    
                }
        
        if(emailId.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter an email id before buying the product");
            return;
        }
       
         sendMail(emailId);
        //Email Sending part
        
        
        //pdf part
        Document document = new Document();
      try
      {
         PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("HelloWorld.pdf"));
         document.open();
         document.add(new Paragraph("A Hello World PDF document."));
         document.close();
         writer.close();
      } catch (DocumentException e)
      {
         e.printStackTrace();
      } catch (Exception e)
      {
         e.printStackTrace();
      }
        //pdf part
        Organization org = null;
     for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
          if (enterprise instanceof RehabCentersEnterprise){     
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PhysiotherapistOrganization){
                org = organization;               
                     
            } 
          }
        }      
     }   
     if(org!=null)
     {
      org.getWorkQueue().getWorkRequestList().add(patientrequest);
            patientrequest.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(patientrequest);
     }
     JOptionPane.showMessageDialog(null, "Requested to Pharmacotherapist");
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
      
    }                                          

    
      public void sendMail(String emailId)
    {
    final String username = "bookmymovie13@gmail.com";
		final String password = "ijklmn786@";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
		  new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		  });

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress("sojitradharti15@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
				InternetAddress.parse(emailId));
			message.setSubject("pharmacotherapist Request");
			message.setText("pharmacotherapist Request sent successfuly.");

			Transport.send(message);

			//System.out.println("Done");

		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
                 patientrequest.setStatus("Assigned to pharmacotherapist");
                 popupResult();
	}
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }                                        

    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {    
        
          RequestPharmacistForMedicine medPanel = new RequestPharmacistForMedicine(userProcessContainer, patientrequest, network, userAccount,  enterprise);
        
       
            userProcessContainer.add("processWorkRequestJPanel", medPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();

            layout.next(userProcessContainer);
            JOptionPane.showMessageDialog(null, "Request sent back to Doctor");
            popupResult();
    }                                               

    private void btnPsycActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:

        Organization org = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof RehabCentersEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof PsychiatristOrganization) {
                        org = organization;
                        break;
                    }
                }
            }
        }
        if (org != null) {
            //int a =org.getWorkQueue().getWorkRequestList().hashCode();
            org.getWorkQueue().getWorkRequestList().add(patientrequest);
            patientrequest.setReceiver(null);
            userAccount.getWorkQueue().getWorkRequestList().add(patientrequest);
        }
        patientrequest.setStatus("Assigned to psychiatrist");
         JOptionPane.showMessageDialog(null, "Request sent to psychiatrist");
          popupResult();
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnPsyc;
    private javax.swing.JButton btnphrmaco;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtResultType;
    private javax.swing.JTextField txtResultbyLab;
    // End of variables declaration                   

    private void popupResult() {
        
        txtName.setText(patientrequest.getSender().getUsername());
        txt.setText(patientrequest.getLabresult());
        txtResultType.setText(patientrequest.getResulttype());
        txtResultbyLab.setText(patientrequest.getSolution());
        String category = txtResultType.getText();
           if(category.contains("Pharmacotherapist"))
           {
               btnPsyc.setEnabled(false);
               btnPrescription.setEnabled(false);
           }
           else if(category.contains("Psychiatrist"))
           {
               btnphrmaco.setEnabled(false);
               btnPrescription.setEnabled(false);
           }
           else if(category.contains("Not Overdose"))
           {
               btnphrmaco.setEnabled(false);
               btnPsyc.setEnabled(false);
           }

    }
}
