/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PhysiotherapistRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PhysiotherapistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sojit
 */
public class treatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form treatJPanel
     */
   

  JPanel userProcessContainer;
   UserAccount userAccount;
   PhysiotherapistOrganization organization;
    Enterprise enterprise;
     Network network; 
     WorkRequest request;
     String treatment_methods[] = {"Trauma-Informed Therapy", "Diet, Nutrition , & Wellness Therapy", "Group Therapy", "Individual Therapy","Come for Cognitive Behavioral Therapy"};

    treatJPanel(JPanel userProcessContainer, UserAccount userAccount, PhysiotherapistOrganization organization, Enterprise enterprise, Network network, WorkRequest request) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.userAccount = userAccount;
    this.organization = organization;
    this.enterprise = enterprise;
    this.network = network;
    this.request = request;
    Loadddl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsenddecision = new javax.swing.JButton();
        ddlmeetings = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(188, 194, 223));

        jLabel1.setText("Select meeting frequency");

        btnsenddecision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsenddecision.setText("Send Decision to patient");
        btnsenddecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsenddecisionActionPerformed(evt);
            }
        });

        ddlmeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlmeetingsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pharmacotherapist Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsenddecision, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(ddlmeetings, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ddlmeetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnsenddecision)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsenddecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsenddecisionActionPerformed
     request.setDiagnose( (String )ddlmeetings.getSelectedItem() + " is recommended by  Phrmacotherapist" );
     JOptionPane.showMessageDialog(null, "Decision sent to patient ");
    }//GEN-LAST:event_btnsenddecisionActionPerformed

    private void ddlmeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlmeetingsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ddlmeetingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsenddecision;
    private javax.swing.JComboBox ddlmeetings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void Loadddl() {
        for(String str: treatment_methods)
       {
           ddlmeetings.addItem(str);
       }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
